version: "3.10"
   
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:5555"  
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    container_name: classroom

volumes:
  postgres_data:
  media_volume:
  static_volume:
