# Generated by Django 4.1.7 on 2023-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=1, max_length=8, unique=True, verbose_name='Код курса'),
            preserve_default=False,
        ),
    ]
