# Generated by Django 4.1.7 on 2023-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(editable=False, max_length=8, unique=True, verbose_name='Код курса'),
        ),
    ]
